---
title: "p8105_hw5_zj2357"
author: "Zekai Jin"
date: "2022-11-05"
output: github_document
---

First of all, we should include  the libraries we are using and prepare the dataset.
```{r init, message=FALSE}
library(tidyverse)
knitr::opts_chunk$set(
  message  = FALSE,
  warning = FALSE,
  fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
```

# Problem 1
read and tidy the data
```{r}
f_names = list.files("data", pattern = "(exp|con)_\\d\\d.csv")

joined_df = 
  map_dfr(str_c("data/",f_names),read_csv) %>%
  mutate(
    id = str_replace(f_names, ".csv", ""),
    group = as.factor(str_replace(f_names, "_\\d\\d.csv", ""))
  ) %>%
  select(id, group, everything()) 

write_csv(joined_df, "data/tidy/result.csv")
```

making a plot
```{r}
joined_df %>%
  pivot_longer(
    week_1:week_8,
    names_to = "week",
    names_prefix = "week_",
    values_to = "value"
  ) %>%
  mutate(week = as.numeric(week)) %>%
  ggplot(aes(x = week,y = value, color = group, group = id)) +
  geom_line()
```


# Problem 2

```{r}
rm(list = ls())

homi_df = read_csv("data/homicide-data.csv")
```


```{r}
homi_df = 
  homi_df %>%
  mutate(
    city_state = str_c(city, ",", state) 
  ) %>%
  group_by(city_state) %>%
  summarise(
    n_obs = n(),
    unsolved = sum(disposition %in% c("Closed without arrest","Open/No arrest"))
  )
  
homi_filt = filter(homi_df,city_state == "Baltimore,MD")
test_res =  prop.test(x = homi_filt$unsolved, n = homi_filt$n_obs)
save(test_res, file = "results/prop_test_BMD.RData")
broom::tidy(test_res) %>%
  select(estimate, conf.low,conf.high)
```

```{r}
conf_int =
  map2_df(.x = homi_df$unsolved, .y = homi_df$n_obs, .f =  ~broom::tidy(prop.test(.x,.y))) %>%
  mutate(city_state = homi_df$city_state) %>%
  select(city_state, estimate, conf.low,conf.high)

conf_int
```

```{r}
conf_int %>%
  mutate(
    city_state = fct_reorder(city_state, -estimate)
  ) %>%
  ggplot(aes(x = estimate, y = city_state)) +
  geom_point()+
  geom_errorbar(aes(xmin = conf.low, xmax = conf.high))
```









# Problem 3







